### ISSUE TITLE
Records are not showing in Excel(CSV) file. 

### ISSUE THREAD

**Issue by 23bca274** [vtcbca/internal-exam-23bca274#2]
please help me to solve this .

**Comment by 23BCA281** [comment]
> please help me to solve this .

could you please send your complete code .

**Comment by 23BCA284** [comment]
upload your complete code

**Comment by amitvtcbb** [comment]
MANUALLY CHECK, IS THERE ANY CONTENT IN FILE? IF NOT , THEN RECHECK YOUR CODE SPECIALLY STATEMENTS WHICH ARE USED TO WRITE THE CONTENT.

**Comment by 23bca274** [comment]
> MANUALLY CHECK, IS THERE ANY CONTENT IN FILE? IF NOT , THEN RECHECK YOUR CODE SPECIALLY STATEMENTS WHICH ARE USED TO WRITE THE CONTENT.

Ok, i got my mistake Sir !

**Comment by amitvtcbb** [comment]
if issue solved, pleas close with final comment. like  thank you for your help or suggestion.

**Comment by 23bca274** [comment]
Thank you all for your help and suggestions which helped me a lot !
