### ISSUE TITLE
please solve this error .

### ISSUE THREAD

**Issue by 23bca274** [vtcbca/internal-exam-23bca274#3]
how to total and print total of all fees
how to count remaining fee and print total of remaining fee

![Screenshot (81)](https://github.com/user-attachments/assets/ab6bba0a-e1c0-4b80-8c26-3ab382d533d5)

**Comment by 23BCA284** [comment]
here in question is already maintioned that total fee of bba is 13400 and bca is 15400
when you  create output_file where you can show in the output file how fee has been paid by the students and how much fee is left from the total fee stated.
And the total fee is already involved in your question.

**Comment by 23bca274** [comment]
So I've to create another file where I can show remaining fees ??

**Comment by 23BCA284** [comment]
for row in rows:
      student_id,name,dept,paidfee=row
      remaining_fee = total_fees[dept]-paidfee
      writer.writerow(row+[remaining_fee])


You can relate your code like this and modify in your way I hope it is help you to solving your error.

**Comment by 23BCA284** [comment]
> So I've to create another file where I can show remaining fees ??

no need you can also add remaininf_fee in your main file

**Comment by 23bca274** [comment]
I've tried your provided logic already but it's not working

**Comment by 23bca274** [comment]
> for row in rows:
>       student_id,name,dept,paidfee=row
>       remaining_fee = total_fees[dept]-paidfee
>       writer.writerow(row+[remaining_fee])
> 
> 
> You can relate your code like this and modify in your way I hope it is help you to solving your error.

I've tried your provided logic already but it's not working

**Comment by amitvtcbb** [comment]
PLEASE CHECK YOUR PROGRAM FLOW:

1. OPEN AND CREATE FILE. WHEN ENTER YOU RECORD PLEASE CONSIDER DEPARTMENT AND THEIR FEES ARE GIVEN ALREADY IN PROGRAM.
2. CREATE ONE MORE CSV FILE TO WRITE DATA WITH REMAINING FEES.
3. AFTER CREATING FILE, READ FILE ONE BY ONE RECORD AND APPEND EACH DATA INTO LIST.

**NOTE:** WHEN YOU READ CSV FILE , ALL YOUR DATA CONSIDER AS TEXT, SO YOU HAVE TO CONVERT YOUR PAID FEE DATA INTO INTEGER. 

4. NOW CALCULATE REMAINING FEE. STORE ALL THIS DATA INTO LIST.
5. NOW WRITE LIST DATA INTO ANOTHER FILE.

**Comment by 23bca274** [comment]
> PLEASE CHECK YOUR PROGRAM FLOW:
> 
> 1. OPEN AND CREATE FILE. WHEN ENTER YOU RECORD PLEASE CONSIDER DEPARTMENT AND THEIR FEES ARE GIVEN ALREADY IN PROGRAM.
> 2. CREATE ONE MORE CSV FILE TO WRITE DATA WITH REMAINING FEES.
> 3. AFTER CREATING FILE, READ FILE ONE BY ONE RECORD AND APPEND EACH DATA INTO LIST.
> 
> **NOTE:** WHEN YOU READ CSV FILE , ALL YOUR DATA CONSIDER AS TEXT, SO YOU HAVE TO CONVERT YOUR PAID FEE DATA INTO INTEGER.
> 
> 4. NOW CALCULATE REMAINING FEE. STORE ALL THIS DATA INTO LIST.
> 5. NOW WRITE LIST DATA INTO ANOTHER FILE.

Thank You Sir , the steps you provided helped me a lot !

**Comment by amitvtcbb** [comment]
if you got answer , please close the issue by writing final comment.

**Comment by 23bca274** [comment]
> for row in rows:
>       student_id,name,dept,paidfee=row
>       remaining_fee = total_fees[dept]-paidfee
>       writer.writerow(row+[remaining_fee])
> 
> 
> You can relate your code like this and modify in your way I hope it is help you to solving your error.


Thank you for your suggestion
